modLoader="javafml"
loaderVersion="${mod_forge_version}"
# issueTrackerURL="https://minecraft.curseforge.com/projects/x/issues"
# displayURL="https://minecraft.curseforge.com/projects/x"
# logoFile="advancedtools.png"
# credits=""
authors="${mod_vendor}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://maxhenkel.de/update/advancedtools.json"
description='''
Advanced Tools
'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${mod_forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mod_minecraft_version}]"
    ordering="NONE"
    side="BOTH"